branch-defaults:
  default:
    environment: Udacityudagramapp-env-1
deploy:
  artifact: www/Archive.zip
environment-defaults:
  Udacityudagramapp-env:
    branch: null
    repository: null
global:
  application_name: udacity-udagram-app
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
